export default {
  colors: {
    primary: '#f25c50',
    grey: '#f7f7f7',
    black: 'black',
    lightGrey: '#e4e6e7',
    veryLightGrey: '#f4f4f4',
    mediumgrey: '#333',
    darkgrey: '#2e333d',
    white: '#fff',
    buttonblack: '#2e333d',
    infotextcolor: '#3f4145',
    green: '#66CDAA',
    silver: '#A9A9A9',
    gery_original: '#8e8e8e',
    classyGrey: '#6f7176',
    cartContainerBackground: '#fafafa',
    backgroundGrey: '#f9fafa',
    orderBorderGrey: '#e2e2e2',
    addressTextInfoGrey: '#72757a',
    inputFieldBorder: '#dadcde',
    dropDownColor: '#fcfcfc',
    offerCardBackground: '#7C7C7C',
    transparent: 'rgba(52, 52, 52, 0.03)',
    borderColor: '#ccc',
  },
};
